---

# Test01: Create directory where goss should be downloaded
- name: "Converge 01 | Full default variables"
  hosts: all
  become: true
  gather_facts: False

  roles:
    - role: ansible-goss-install
      goss_dst_dir: /bin_goss

# Test02: DO NOT create directory where goss should be downloaded
- name: "Converge 02 | DO NOT Create directory for goss"
  hosts: all
  become: true
  gather_facts: False

  roles:
    - role: ansible-goss-install
      goss_dst_dir: /bin_goss
      goss_create_dst_dir: False

  post_tasks:
    - name: "CMD: Run 'ls' command against /bin_goss directory"
      command: ls -la /bin_goss
      register: cmd
      changed_when: False

    - name: "DEBUG: Display details about command above"
      debug:
        var: cmd.stdout_lines
